// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type Record interface {
	IsRecord()
}

type AddPlayerInput struct {
	Name    string `json:"name"`
	EventID string `json:"eventID"`
}

type Event struct {
	ID           string           `json:"id"`
	CreatedAt    time.Time        `json:"createdAt"`
	UpdatedAt    time.Time        `json:"updatedAt"`
	Name         string           `json:"name"`
	Description  string           `json:"description"`
	Type         EventType        `json:"type"`
	Published    bool             `json:"published"`
	Registration RegistrationType `json:"registration"`
	Days         []*EventDay      `json:"days"`
	Organizer    *User            `json:"organizer"`
	HeadJudge    *User            `json:"headJudge"`
	Judges       []*User          `json:"judges"`
	Players      []*Player        `json:"players"`
}

func (Event) IsRecord() {}

type EventDay struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	EndAt     time.Time `json:"endAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Rounds    []*Round  `json:"rounds"`
	StartAt   time.Time `json:"startAt"`
}

func (EventDay) IsRecord() {}

type EventDayInput struct {
	ID      *string       `json:"id"`
	EndAt   time.Time     `json:"endAt"`
	Rounds  []*RoundInput `json:"rounds"`
	StartAt time.Time     `json:"startAt"`
}

type EventInput struct {
	ID           *string           `json:"id"`
	Name         string            `json:"name"`
	Description  string            `json:"description"`
	Type         EventType         `json:"type"`
	Published    *bool             `json:"published"`
	Registration *RegistrationType `json:"registration"`
	Days         []*EventDayInput  `json:"days"`
	HeadJudge    *string           `json:"headJudge"`
	Judges       []*string         `json:"judges"`
	Players      []*string         `json:"players"`
}

type Match struct {
	ID                     string    `json:"id"`
	CreatedAt              time.Time `json:"createdAt"`
	UpdatedAt              time.Time `json:"updatedAt"`
	Player1                *Player   `json:"player1"`
	Player1VictoryPoints   int       `json:"player1VictoryPoints"`
	Player1MarginOfVictory int       `json:"player1MarginOfVictory"`
	Player2                *Player   `json:"player2"`
	Player2VictoryPoints   int       `json:"player2VictoryPoints"`
	Player2MarginOfVictory int       `json:"player2MarginOfVictory"`
	Bye                    *Player   `json:"bye"`
	Blue                   *Player   `json:"blue"`
	Winner                 *Player   `json:"winner"`
}

func (Match) IsRecord() {}

type MatchInput struct {
	ID                     *string `json:"id"`
	Player1                string  `json:"player1"`
	Player1VictoryPoints   *int    `json:"player1VictoryPoints"`
	Player1MarginOfVictory *int    `json:"player1MarginOfVictory"`
	Player2                string  `json:"player2"`
	Player2VictoryPoints   *int    `json:"player2VictoryPoints"`
	Player2MarginOfVictory *int    `json:"player2MarginOfVictory"`
	Bye                    *string `json:"bye"`
	Blue                   *string `json:"blue"`
	Winner                 *string `json:"winner"`
}

type MatchResultInput struct {
	ImBlue            bool `json:"imBlue"`
	IWon              bool `json:"iWon"`
	MyVictoryPoints   int  `json:"myVictoryPoints"`
	MyMarginOfVictory int  `json:"myMarginOfVictory"`
}

type MatchResultReport struct {
	ID                string    `json:"id"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
	Match             *Match    `json:"match"`
	Reporter          *User     `json:"reporter"`
	ImBlue            bool      `json:"imBlue"`
	IWon              bool      `json:"iWon"`
	MyVictoryPoints   int       `json:"myVictoryPoints"`
	MyMarginOfVictory int       `json:"myMarginOfVictory"`
}

func (MatchResultReport) IsRecord() {}

type Player struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Profile struct {
	Account             *User    `json:"account"`
	Username            string   `json:"username"`
	OrganizedEvents     []*Event `json:"organizedEvents"`
	JudgingEvents       []*Event `json:"judgingEvents"`
	ParticipatingEvents []*Event `json:"participatingEvents"`
}

type Round struct {
	Counter int      `json:"counter"`
	ID      string   `json:"id"`
	Matches []*Match `json:"matches"`
}

type RoundInput struct {
	ID      *string       `json:"id"`
	Matches []*MatchInput `json:"matches"`
}

type User struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Picture *string `json:"picture"`
}

type EventType string

const (
	EventTypeLeague EventType = "LEAGUE"
	EventTypeFfgop  EventType = "FFGOP"
	EventTypeOther  EventType = "OTHER"
)

var AllEventType = []EventType{
	EventTypeLeague,
	EventTypeFfgop,
	EventTypeOther,
}

func (e EventType) IsValid() bool {
	switch e {
	case EventTypeLeague, EventTypeFfgop, EventTypeOther:
		return true
	}
	return false
}

func (e EventType) String() string {
	return string(e)
}

func (e *EventType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventType", str)
	}
	return nil
}

func (e EventType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type RegistrationType string

const (
	RegistrationTypeOpen   RegistrationType = "OPEN"
	RegistrationTypeInvite RegistrationType = "INVITE"
	RegistrationTypeClosed RegistrationType = "CLOSED"
)

var AllRegistrationType = []RegistrationType{
	RegistrationTypeOpen,
	RegistrationTypeInvite,
	RegistrationTypeClosed,
}

func (e RegistrationType) IsValid() bool {
	switch e {
	case RegistrationTypeOpen, RegistrationTypeInvite, RegistrationTypeClosed:
		return true
	}
	return false
}

func (e RegistrationType) String() string {
	return string(e)
}

func (e *RegistrationType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RegistrationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RegistrationType", str)
	}
	return nil
}

func (e RegistrationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
